//Auth
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_MY_BOOKINGS = 'SET_MY_BOOKINGS';

//Booking 
export const SET_ORIGIN = 'SET_ORIGIN';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_ROUTE_DATA = 'SET_ROUTE_DATA';
export const SET_DISTANCE_DURATION = 'SET_DISTANCE_DURATION';
export const SET_VEHICLE_TYPES = 'SET_VEHICLE_TYPES';
export const SET_BOOKING_TYPE = 'SET_BOOKING_TYPE';
export const CONFIRM_LOADING = 'CONFIRM_LOADING';